<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.1485" />
    <xacro:property name="base_width" value="0.105" />
    <xacro:property name="base_height" value="0.012" />
    <xacro:property name="wheel_radius" value="0.0205" />
    <xacro:property name="wheel_length" value="0.0175" />
    <xacro:property name="caster_wheel_radius" value="${wheel_radius/2.0}" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry> 
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white" />
        </visual>

        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 ${wheel_radius}" rpy="0 0 0" />

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry> 
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        </collision>

    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="black" />
        </visual>

        <xacro:cylinder_inertia m="1.0" l="${2*wheel_length}" r="${2*wheel_radius}"  xyz="0 0 0" rpy="${pi/2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
        </collision>

    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="black" />
        </visual>

        <xacro:cylinder_inertia m="1.0" l="${2*wheel_length}" r="${2*wheel_radius}"  xyz="0 0 0" rpy="${pi/2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
        </collision>

    </link>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="silver" />
        </visual>

        <xacro:sphere_inertia m="0.5" r="${2*caster_wheel_radius}" xyz="0 0 0" rpy="0 0 0" />

        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        
    </link>

    <link name="footprint_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
       
        <origin xyz="${-base_length/4.0} ${-base_width/2.0 - wheel_length/4.0} ${-base_height/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length/4.0} ${base_width/2 + wheel_length/4.0} ${-base_height/2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length/4.0} 0 ${-caster_wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="footprint_base_joint" type="fixed">
        <parent link="footprint_link" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

</robot>